version: '3.8'

# Create a dedicated network for TaskVision DynamoDB
networks:
  taskvision-network:
    driver: bridge

# Persistent volumes for DynamoDB data
volumes:
  taskvision-dynamodb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/.local/share/taskvision/dynamodb-data

services:
  # Local DynamoDB instance
  taskvision-dynamodb:
    image: "amazon/dynamodb-local:latest"
    container_name: taskvision-dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000"
    volumes:
      - taskvision-dynamodb-data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    environment:
      - JAVA_OPTS=-Xmx1g
    networks:
      - taskvision-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # DynamoDB Admin UI
  taskvision-dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: taskvision-dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://taskvision-dynamodb:8000
    depends_on:
      taskvision-dynamodb:
        condition: service_healthy
    networks:
      - taskvision-network
    restart: unless-stopped