AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TaskVision backend

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Architectures:
      - x86_64

Parameters:
  ClientOriginUrl:
    Type: String
  TableName:
    Type: String
  CustomDomainName:
    Type: String
  HostedZoneId:
    Type: String
  Auth0Domain:
    Type: String
  Auth0Audience:
    Type: String

Resources:

  TaskVisionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.handler
      CodeUri: .
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          AUTH0_DOMAIN: !Ref Auth0Domain
          AUTH0_AUDIENCE: !Ref Auth0Audience
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: !Ref ClientOriginUrl

  CustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref CustomDomainName
      EndpointConfiguration:
        Types: [REGIONAL]
      RegionalCertificateArn:
        Fn::ImportValue: CertificateArn  # or use an explicit ARN if preferred
      SecurityPolicy: TLS_1_2

  BasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref CustomDomain
      RestApiId: !Ref ApiGateway
      Stage: Prod

  Route53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref CustomDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt CustomDomain.RegionalHostedZoneId

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${CustomDomainName}/"
