name: Deploy Backend (Dev)

on:
  push:
    branches: [main, dev]
    paths:
      - '**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev or prod)'
        required: true
        default: dev
        type: choice
        options: [dev, prod]

jobs:
  deploy:
    name: Deploy to AWS SAM (Dev)
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: npm ci
        working-directory: .

      - name: Build SAM application
        run: sam build
        working-directory: .

      - name: Set environment name and prefixes
        id: setenv
        shell: bash
        env:
          INPUT_ENV: ${{ github.event.inputs.environment }}
          GIT_REF: ${{ github.ref_name }}
        run: |
          if [[ "$INPUT_ENV" != "" ]]; then
            echo "env_name=$INPUT_ENV" >> $GITHUB_OUTPUT
          elif [[ "$GIT_REF" == "main" ]]; then
            echo "env_name=prod" >> $GITHUB_OUTPUT
          else
            echo "env_name=dev" >> $GITHUB_OUTPUT
          fi

          if [[ "$INPUT_ENV" == "prod" || "$GIT_REF" == "main" ]]; then
            echo "prefix=" >> $GITHUB_OUTPUT
            echo "apiprefix=api." >> $GITHUB_OUTPUT
          else
            echo "prefix=dev." >> $GITHUB_OUTPUT
            echo "apiprefix=dev-api." >> $GITHUB_OUTPUT
          fi

      - name: Debug: Print template.yaml
        run: cat template.yaml

      - name: Deploy to AWS
        run: |
          sam deploy \
            --stack-name taskvision-${{ steps.setenv.outputs.env_name }}-backend \
            --region ${{ secrets.AWS_REGION }} \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --force-upload \
            --s3-prefix taskvision-${{ steps.setenv.outputs.env_name }} \
            --parameter-overrides \
              Environment=${{ steps.setenv.outputs.env_name }} \
              ClientOriginUrl=https://${{ steps.setenv.outputs.prefix }}${{ secrets.DOMAIN_NAME }} \
              TableName=${{ secrets.TABLE_NAME }} \
              CustomDomainName=${{ steps.setenv.outputs.apiprefix }}${{ secrets.DOMAIN_NAME }} \
              CertificateArn=${{ secrets.CERTIFICATE_ARN }}
        working-directory: .
