AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend API for TaskVision with custom domain and Route 53 support

Parameters:
  ClientOriginUrl:
    Type: String
    Default: '*'
    Description: Allowed CORS origin URL

  TableName:
    Type: String
    Description: Name of an existing DynamoDB table

  CustomDomainName:
    Type: String
    Default: api.taskvision.ai
    Description: Custom domain for API Gateway

  HostedZoneId:
    Type: String
    Description: Route 53 Hosted Zone ID for domain validation

  AUTH0_ISSUER_BASE_URL:
    Type: String
    Description: Auth0 issuer base URL

  AUTH0_AUDIENCE:
    Type: String
    Description: Auth0 audience

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: !Ref ClientOriginUrl
        MaxAge: "'86400'"

  TaskVisionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .aws-sam/build/TaskVisionFunction
      Handler: lambda.handler
      Runtime: nodejs18.x
      Architectures: [x86_64]
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          CLIENT_ORIGIN_URL: !Ref ClientOriginUrl
          AUTH0_ISSUER_BASE_URL: !Ref AUTH0_ISSUER_BASE_URL
          AUTH0_AUDIENCE: !Ref AUTH0_AUDIENCE
          NODE_ENV: "production"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref CustomDomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref CustomDomainName
          HostedZoneId: !Ref HostedZoneId

  CustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref CustomDomainName
      RegionalCertificateArn: !Ref Certificate
      EndpointConfiguration:
        Types: [REGIONAL]

  BasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref CustomDomain
      RestApiId: !Ref ApiGateway
      Stage: Prod

  Route53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: taskvision.ai.
      Name: !Ref CustomDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt CustomDomain.RegionalHostedZoneId

Outputs:
  ApiUrl:
    Description: "Deployed API Gateway custom domain"
    Value: !Sub "https://${CustomDomainName}/"

