AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TaskVision Backend API

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

  ClientOriginUrl:
    Type: String
    Description: Allowed CORS origin URL

  TableName:
    Type: String
    Description: DynamoDB table name

  CustomDomainName:
    Type: String
    Description: Custom domain name for API Gateway

  CertificateArn:
    Type: String
    Description: ACM certificate ARN for custom domain

Resources:
  TaskVisionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'!Ref ClientOriginUrl'"
      Domain:
        DomainName: !Ref CustomDomainName
        CertificateArn: !Ref CertificateArn
        EndpointConfiguration: REGIONAL
        SecurityPolicy: TLS_1_2

  TaskVisionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          ENVIRONMENT: !Ref Environment
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TaskVisionApi
            Path: /{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
