AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TaskVision backend infrastructure

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    MemorySize: 128
    Architectures:
      - x86_64

Parameters:
  ClientOriginUrl:
    Type: String
  TableName:
    Type: String
  CustomDomainName:
    Type: String
  HostedZoneId:
    Type: String
  Auth0Domain:
    Type: String
  Auth0Audience:
    Type: String
  CertificateArn:
    Type: String
    Description: ARN of the existing ACM certificate

Resources:

  TaskVisionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/lambda.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          CLIENT_ORIGIN_URL: !Ref ClientOriginUrl
          AUTH0_DOMAIN: !Ref Auth0Domain
          AUTH0_AUDIENCE: !Ref Auth0Audience
      Events:
        ProxyApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY

  CustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref CustomDomainName
      CertificateArn: !Ref CertificateArn
      EndpointConfiguration:
        Types:
          - EDGE

  BasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref CustomDomain
      RestApiId: !Ref ServerlessRestApi
      Stage: Prod

  Route53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref CustomDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CustomDomain.DistributionDomainName
        HostedZoneId: Z2FDTNDATAQYW2  # This is the standard for CloudFront

Outputs:
  ApiUrl:
    Description: API Gateway endpoint
    Value: !Sub "https://${CustomDomainName}/"
  FunctionName:
    Description: Name of Lambda function
    Value: !Ref TaskVisionFunction
