AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TaskVision backend infrastructure – deploys Lambda and API only

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    MemorySize: 128
    Architectures:
      - x86_64

Parameters:
  ClientOriginUrl:
    Type: String
  TableName:
    Type: String
  Auth0Domain:
    Type: String
  Auth0Audience:
    Type: String

Resources:

  TaskVisionApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: TaskVisionApi
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowHeaders: "'Authorization,Content-Type,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: !Sub "'${ClientOriginUrl}'"
        MaxAge: "'86400'"

  TaskVisionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/lambda.handler
      Events:
        ProxyApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref TaskVisionApi
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          CLIENT_ORIGIN_URL: !Ref ClientOriginUrl
          AUTH0_DOMAIN: !Ref Auth0Domain
          AUTH0_AUDIENCE: !Ref Auth0Audience

Outputs:
  ApiUrl:
    Description: API Gateway endpoint (default)
    Value: !Sub "https://${TaskVisionApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  FunctionName:
    Description: Name of Lambda function
    Value: !Ref TaskVisionFunction
