AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Minimal backend API for TaskVision (Lambda + API Gateway)

Parameters:
  ClientOriginUrl:
    Type: String
    Default: '*'
    Description: Allowed CORS origin URL

  TableName:
    Type: String
    Description: Name of an existing DynamoDB table

  Auth0Domain:
    Type: String
    Description: Auth0 domain

  Auth0Audience:
    Type: String
    Description: Auth0 audience

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: taskvision-backend
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: !Sub "'${ClientOriginUrl}'"
        MaxAge: "'86400'"

  TaskVisionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/lambda.handler
      Runtime: nodejs18.x
      Architectures: [x86_64]
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          CLIENT_ORIGIN_URL: !Ref ClientOriginUrl
          AUTH0_DOMAIN: !Ref Auth0Domain
          AUTH0_AUDIENCE: !Ref Auth0Audience
          NODE_ENV: "production"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: Default endpoint (for testing only)
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
